### ISSUE TITLE
based_on doesn't seem to work with linq

### ISSUE THREAD

**Issue by tcovert** [JuliaStats/DataFramesMeta.jl#57] opened 2016-07-13 18:15 UTC
when I try to use based_on within a linq call, I get an undef_var error.  here is a MWE:

`using DataFrames, DataFramesMeta
df = DataFrame(id = [1, 1, 2, 2, 3, 3], vals = randn(6))
@linq df |> groupby(:id) |> based_on(totval = sum(vals))`

for me, the result is a red: "ERROR: UndefVarError: based_on not defined"

here is the output of Pkg.status(DataFramesMeta)
`julia> Pkg.status("DataFramesMeta")
 - DataFramesMeta                0.1.1
`

any idea why this doesn't work?

**Comment by ararslan** [comment] 2016-07-13 18:34
Looks like you need to call `based_on` as a macro and make `vals` a symbol in the call.

```julia
julia> @linq df |> groupby(:id) |> @based_on(totval = sum(:vals))
3×2 DataFrames.DataFrame
│ Row │ id │ totval    │
├─────┼────┼───────────┤
│ 1   │ 1  │ -0.875715 │
│ 2   │ 2  │ -1.19077  │
│ 3   │ 3  │ -0.621758 │
```

**Comment by ararslan** [comment] 2016-07-13 19:52
Ah, this is a duplicate of #48, which was fixed in https://github.com/JuliaStats/DataFramesMeta.jl/commit/fdd3d7f50630ba1ea755d68ce01eab0469ebc353. A new release hasn't been tagged since then. Once a new version is released, you should be able to `Pkg.update()` and it should work as expected.

**Closed by ararslan** 2016-07-13 19:52 UTC
